language: node_js
node_js:
  - 16.15.1

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-feed luongtrung/udagram-api-feed:v8
  - docker tag udagram-api-user luongtrung/udagram-api-user:v8
  - docker tag udagram-frontend luongtrung/udagram-frontend:v8
  - docker tag reverseproxy luongtrung/reverseproxy:v8

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push luongtrung/udagram-api-feed:v8
  - docker push luongtrung/udagram-api-user:v8
  - docker push luongtrung/udagram-frontend:v8
  - docker push luongtrung/reverseproxy:v8
